/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.bestmusicplayer;

import com.google.gson.Gson; 
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;


/**
 *
 * @author Juan
 */
public class NewMainJFrame extends javax.swing.JFrame {

    String email = "";
    String password = "";
    String search = "";
    
    String createEmail = "";
    String createPassword = "";
    String createConfirmPassword = "";
    
    String createPlaylistName = "";
    String createPlaylistDescription = "";
    
    Mp3 player;    
    String songFile;
    Login loginObj = new Login();
    CreateAccount createAccountObj = new CreateAccount();
    CreatePlaylist createPlaylistObj = new CreatePlaylist();
    
    /**
     * Creates new form NewMainJFrame
     */
    public NewMainJFrame() {
        initComponents();
        songFile = "imperial.mp3";
        player = new Mp3(songFile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        loginTitle = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        createPageButton = new javax.swing.JButton();
        test = new javax.swing.JPanel();
        PlayButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        Progress = new javax.swing.JSlider();
        viewCreatePlaylistButton = new javax.swing.JButton();
        createAccount = new javax.swing.JPanel();
        createTitle = new javax.swing.JLabel();
        createEmailLabel = new javax.swing.JLabel();
        createPasswordLabel = new javax.swing.JLabel();
        createConfirmLabel = new javax.swing.JLabel();
        createEmailField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        createPasswordField = new javax.swing.JPasswordField();
        createConfirmPasswordField = new javax.swing.JPasswordField();
        createPlaylist = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        createPlaylistTitle = new javax.swing.JLabel();
        createPlaylistNameLabel = new javax.swing.JLabel();
        createPlaylistNameField = new javax.swing.JTextField();
        createPlaylistDescriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        createPlaylistDescriptionTextArea = new javax.swing.JTextArea();
        createPlaylistButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(51, 255, 102));

        loginTitle.setText("Spotify Login");

        emailLabel.setText("Email:");

        passwordLabel.setText("Password:");

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        createPageButton.setText("Create Account");
        createPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addGap(18, 18, 18)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginButton)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addGap(43, 43, 43)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginTitle)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(createPageButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(loginTitle)
                .addGap(63, 63, 63)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createPageButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        main.add(login, "card2");

        PlayButton.setText("Play");
        PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayButtonMouseClicked(evt);
            }
        });

        StopButton.setText("Stop");
        StopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StopButtonMouseClicked(evt);
            }
        });

        Progress.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                ProgressCaretPositionChanged(evt);
            }
        });

        viewCreatePlaylistButton.setText("Create a Playlist");
        viewCreatePlaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCreatePlaylistButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout testLayout = new javax.swing.GroupLayout(test);
        test.setLayout(testLayout);
        testLayout.setHorizontalGroup(
            testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(testLayout.createSequentialGroup()
                .addGroup(testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(testLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(viewCreatePlaylistButton)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        testLayout.setVerticalGroup(
            testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(viewCreatePlaylistButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(testLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(StopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addComponent(PlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        main.add(test, "card3");

        createTitle.setText("Create Account");

        createEmailLabel.setText("Email:");

        createPasswordLabel.setText("Password:");

        createConfirmLabel.setText("Confirm Password:");

        createEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmailFieldActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountLayout = new javax.swing.GroupLayout(createAccount);
        createAccount.setLayout(createAccountLayout);
        createAccountLayout.setHorizontalGroup(
            createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createPasswordLabel)
                    .addComponent(createEmailLabel)
                    .addComponent(createConfirmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(createPasswordField)
                    .addComponent(createConfirmPasswordField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountLayout.createSequentialGroup()
                        .addComponent(createTitle)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountLayout.createSequentialGroup()
                        .addComponent(createButton)
                        .addGap(240, 240, 240))))
        );
        createAccountLayout.setVerticalGroup(
            createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(createTitle)
                .addGap(60, 60, 60)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmailLabel)
                    .addComponent(createEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPasswordLabel)
                    .addComponent(createPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createConfirmLabel)
                    .addComponent(createConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        main.add(createAccount, "card4");

        createPlaylistTitle.setText("Create a Playlist");

        createPlaylistNameLabel.setText("Playlist Name:");

        createPlaylistNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlaylistNameFieldActionPerformed(evt);
            }
        });

        createPlaylistDescriptionLabel.setText("Description:");

        createPlaylistDescriptionTextArea.setColumns(20);
        createPlaylistDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(createPlaylistDescriptionTextArea);

        createPlaylistButton.setText("Create");
        createPlaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlaylistButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createPlaylistTitle)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(createPlaylistNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(createPlaylistNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(createPlaylistDescriptionLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(createPlaylistButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(createPlaylistTitle)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPlaylistNameLabel)
                    .addComponent(createPlaylistNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createPlaylistDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createPlaylistButton)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout createPlaylistLayout = new javax.swing.GroupLayout(createPlaylist);
        createPlaylist.setLayout(createPlaylistLayout);
        createPlaylistLayout.setHorizontalGroup(
            createPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPlaylistLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        createPlaylistLayout.setVerticalGroup(
            createPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPlaylistLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        main.add(createPlaylist, "card5");

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        email = emailField.getText();
        password = String.valueOf(passwordField.getPassword());
        
        loginObj.logging_in(email, password, main, test);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void PlayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseClicked
        player.mp3play();
    }//GEN-LAST:event_PlayButtonMouseClicked

    private void StopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopButtonMouseClicked
        player.stop();
    }//GEN-LAST:event_StopButtonMouseClicked

    private void ProgressCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ProgressCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgressCaretPositionChanged

    private void createPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPageButtonActionPerformed
        createAccountObj.view_create(main, createAccount);
    }//GEN-LAST:event_createPageButtonActionPerformed

    private void createEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEmailFieldActionPerformed

    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        createEmail = createEmailField.getText();
        createPassword = String.valueOf(createPasswordField.getPassword());
        createConfirmPassword = String.valueOf(createConfirmPasswordField.getPassword());
        
        if(createAccountObj.creating_account(createEmail, createPassword, createConfirmPassword))
        {
            System.out.print("logging in");
            loginObj.logging_in(createEmail, createPassword, main, test);
        }
        else
        {
            System.out.print("not successful");
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void viewCreatePlaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCreatePlaylistButtonActionPerformed
        //  This button will take user to create a playlist page when clicked
      
            createPlaylistObj.view_createPlaylist(main, createPlaylist);
            
    }//GEN-LAST:event_viewCreatePlaylistButtonActionPerformed

    private void createPlaylistNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlaylistNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPlaylistNameFieldActionPerformed

    private void createPlaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlaylistButtonActionPerformed
        createPlaylistName = createPlaylistNameField.getText();
        createPlaylistDescription = createPlaylistDescriptionTextArea.getText();
        
        createPlaylistObj.create_playlist(createPlaylistName, createPlaylistDescription);
        
        if(createPlaylistObj.create_playlist(createPlaylistName, createPlaylistDescription))
        {
            loginObj.view_homePage(main, test);
        }
        else
        {
            System.out.print("Could not create playlist");
        }
    }//GEN-LAST:event_createPlaylistButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayButton;
    private javax.swing.JSlider Progress;
    private javax.swing.JButton StopButton;
    private javax.swing.JPanel createAccount;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel createConfirmLabel;
    private javax.swing.JPasswordField createConfirmPasswordField;
    private javax.swing.JTextField createEmailField;
    private javax.swing.JLabel createEmailLabel;
    private javax.swing.JButton createPageButton;
    private javax.swing.JPasswordField createPasswordField;
    private javax.swing.JLabel createPasswordLabel;
    private javax.swing.JPanel createPlaylist;
    private javax.swing.JButton createPlaylistButton;
    private javax.swing.JLabel createPlaylistDescriptionLabel;
    private javax.swing.JTextArea createPlaylistDescriptionTextArea;
    private javax.swing.JTextField createPlaylistNameField;
    private javax.swing.JLabel createPlaylistNameLabel;
    private javax.swing.JLabel createPlaylistTitle;
    private javax.swing.JLabel createTitle;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPanel main;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel test;
    private javax.swing.JButton viewCreatePlaylistButton;
    // End of variables declaration//GEN-END:variables
}
